

export const menuData = {
  entradas: [
    { id:1, name:"Kimchi", img:"../items/Kimchi.jpg", desc:"Col fermentada con chile, ajo y jengibre; sabor intenso y picante.", price:85, spicy:true, veg:true },
    { id:2, name:"Kkakdugi", img:"../items/Kkakdugi.jpg", desc:"Rábano fermentado en cubos, crujiente y con toque picante.", price:85, spicy:true, veg:true },
    { id:3, name:"Japchae", img:"../items/Japchae.jpg", desc:"Fideos de camote salteados con verduras y salsa de soya dulce.", price:145 },
    { id:4, name:"Mandu", img:"../items/Mandu.jpg", desc:"Empanadillas coreanas rellenas de carne y verduras.", price:130 },
    { id:5, name:"Pajeon", img:"../items/Pajeon.jpg", desc:"Panqueque salado de cebollín, crujiente por fuera.", price:120, veg:true },
    { id:6, name:"Kimchi Jeon", img:"../items/Kimchi Jeon.jpg", desc:"Panqueque con kimchi, con sabor fuerte y picante.", price:125, spicy:true },
    { id:7, name:"Tteokbokki", img:"../items/Tteokbokki.jpg", desc:"Pasteles de arroz en salsa picante y ligeramente dulce.", price:135, spicy:true },
    { id:8, name:"Gyeran Jjim", img:"../items/Gyeran Jjim.jpg", desc:"Huevo al vapor suave y esponjoso.", price:90, veg:true },
    { id:9, name:"Oi Muchim", img:"../items/Oi Muchim.jpg", desc:"Ensalada fresca de pepino con toque picante.", price:95, spicy:true, veg:true },
    { id:10, name:"Sigeumchi Namul", img:"../items/Sigeumchi Namul.jpg", desc:"Espinaca sazonada con aceite de sésamo y ajo.", price:90, veg:true },
    { id:11, name:"Gamja Salad", img:"../items/Gamja Salad.jpg", desc:"Ensalada cremosa de papa con verduras.", price:100, veg:true },
    { id:12, name:"Eomuk Bokkeum", img:"../items/Eomuk Bokkeum.jpg", desc:"Pastel de pescado salteado con salsa de soya.", price:115 },
  ],

  principales: [
    { id:13, name:"Bibimbap", img:"../items/Bibimbap.jpg", desc:"Arroz con vegetales, carne, huevo y pasta picante mezclado.", price:195, spicy:true },
    { id:14, name:"Bulgogi", img:"../items/Bulgogi.jpg", desc:"Res marinada en salsa dulce de soya, jugosa y suave.", price:225 },
    { id:15, name:"Samgyeopsal", img:"../items/Samgyeopsal.jpg", desc:"Panceta de cerdo a la parrilla servida con hojas.", price:235 },
    { id:16, name:"Galbi", img:"../items/Galbi.jpg", desc:"Costillas marinadas, tiernas y caramelizadas.", price:260 },
    { id:17, name:"Jjajangmyeon", img:"../items/Jjajangmyeon.jpg", desc:"Fideos con salsa espesa de frijol negro.", price:175 },
    { id:18, name:"Jjamppong", img:"../items/Jjamppong.jpg", desc:"Sopa picante de mariscos con fideos.", price:185, spicy:true },
    { id:19, name:"Kimchi Jjigae", img:"../items/Kimchi Jjigae.jpg", desc:"Guiso caliente de kimchi con tofu y carne.", price:175, spicy:true },
    { id:20, name:"Sundubu Jjigae", img:"../items/Sundubu Jjigae.jpg", desc:"Sopa picante con tofu suave y caldo intenso.", price:170, spicy:true },
    { id:21, name:"Dakgalbi", img:"../items/Dakgalbi.jpg", desc:"Pollo salteado con verduras en salsa picante.", price:180, spicy:true },
    { id:22, name:"Naengmyeon", img:"../items/Naengmyeon.jpg", desc:"Fideos fríos en caldo ligero y refrescante.", price:165 },
    { id:23, name:"Bossam", img:"../items/Bossam.jpg", desc:"Cerdo hervido servido con hojas para envolver.", price:195 },
    { id:24, name:"Gamjatang", img:"../items/Gamjatang.jpg", desc:"Sopa espesa de hueso de cerdo con papas.", price:185, spicy:true },
    { id:25, name:"Seolleongtang", img:"../items/Seolleongtang.jpg", desc:"Caldo blanco de res suave y nutritivo.", price:175 },
    { id:26, name:"Haemul Pajeon", img:"../items/Haemul Pajeon.jpg", desc:"Panqueque crujiente con mariscos.", price:190 },
    { id:27, name:"Dak Kalguksu", img:"../items/Dak Kalguksu.jpg", desc:"Sopa casera de pollo con fideos gruesos.", price:170 },
    { id:28, name:"Gimbap", img:"../items/Gimbap.jpg", desc:"Rollos de arroz con vegetales y proteína.", price:155 },
    { id:29, name:"Ojingeo Bokkeum", img:"../items/Ojingeo Bokkeum.jpg", desc:"Calamar salteado en salsa picante.", price:195, spicy:true },
    { id:30, name:"Doenjang Jjigae", img:"../items/Doenjang Jjigae.jpg", desc:"Sopa espesa de pasta de soya fermentada.", price:170 },
  ],

  postres: [
    { id:31, name:"Bingsu", img:"../items/Bingsu.jpg", desc:"Hielo raspado con frutas y leche condensada.", price:110 },
    { id:32, name:"Hotteok", img:"../items/Hotteok.jpg", desc:"Panqueques rellenos de miel y nueces.", price:95 },
    { id:33, name:"Yakgwa", img:"../items/Yakgwa.jpg", desc:"Galleta frita con miel y especias.", price:80 },
    { id:34, name:"Tteok", img:"../items/Tteok.jpg", desc:"Pasteles de arroz suaves y ligeramente dulces.", price:90 },
    { id:35, name:"Injeolmi", img:"../items/Injeolmi.jpg", desc:"Tteok cubierto con polvo de soya dulce.", price:90 },
    { id:36, name:"Dasik", img:"../items/Dasik.jpg", desc:"Dulces tradicionales prensados y aromáticos.", price:85 },
    { id:37, name:"Hodugwaja", img:"../items/Hodugwaja.jpg", desc:"Panecillos rellenos de nuez y frijol dulce.", price:95 },
    { id:38, name:"Chapssaltteok", img:"../items/Chapssaltteok.jpg", desc:"Bolitas suaves rellenas de pasta dulce.", price:85 },
    { id:39, name:"Gyeongdan", img:"../items/Gyeongdan.jpg", desc:"Bolitas de arroz cubiertas con polvo dulce.", price:80 },
    { id:40, name:"Patbingsu", img:"../items/Patbingsu.jpg", desc:"Bingsu con frijol rojo dulce como topping.", price:120 },
  ],

  bebidas: [
    { id:41, name:"Soju", img:"../items/Soju.jpg", desc:"Licor coreano suave y ligeramente dulce.", price:80, alcohol:true },
    { id:42, name:"Makgeolli", img:"../items/Makgeolli.jpg", desc:"Bebida fermentada de arroz, cremosa y suave.", price:90, alcohol:true },
    { id:43, name:"Sikhye", img:"../items/Sikhye.jpg", desc:"Bebida dulce con granos de arroz flotando.", price:70 },
    { id:44, name:"Boricha", img:"../items/Boricha.jpg", desc:"Té de cebada tostada, sin cafeína.", price:55 },
    { id:45, name:"Yuja cha", img:"../items/Yuja-cha.jpg", desc:"Infusión cítrica dulce con trozos de fruta.", price:70 },
    { id:46, name:"Omija cha", img:"../items/Omija-cha.jpg", desc:"Té con mezcla de sabores dulces y ácidos.", price:75 },
    { id:47, name:"Banana Milk", img:"../items/Banana Milk.jpg", desc:"Bebida láctea dulce con sabor a plátano.", price:65 },
    { id:48, name:"Milkis", img:"../items/Milkis.jpg", desc:"Refresco cremoso con ligera gasificación.", price:60 },
    { id:49, name:"Aloe Drink", img:"../items/Aloe-Drink.jpg", desc:"Bebida refrescante con trozos de aloe.", price:65 },
    { id:50, name:"Korean Green Tea", img:"../items/Korean Green Tea.jpg", desc:"Té verde suave y relajante.", price:60 },
  ]
};


export const tableLayouts = {
  interior: [
    { id:"INT-01", name:"Mesa 1",  seats:2, x:8,  y:12, shape:"round",   zone:"interior" },
    { id:"INT-02", name:"Mesa 2",  seats:2, x:8,  y:30, shape:"round",   zone:"interior" },
    { id:"INT-03", name:"Mesa 3",  seats:4, x:8,  y:50, shape:"rect",    zone:"interior" },
    { id:"INT-04", name:"Mesa 4",  seats:4, x:8,  y:70, shape:"rect",    zone:"interior" },
    { id:"INT-05", name:"Mesa 5",  seats:2, x:8,  y:88, shape:"round",   zone:"interior" },
    { id:"INT-06", name:"Mesa 6",  seats:4, x:30, y:12, shape:"rect",    zone:"interior" },
    { id:"INT-07", name:"Mesa 7",  seats:6, x:30, y:35, shape:"rect-lg", zone:"interior" },
    { id:"INT-08", name:"Mesa 8",  seats:4, x:30, y:62, shape:"rect",    zone:"interior" },
    { id:"INT-09", name:"Mesa 9",  seats:4, x:30, y:83, shape:"rect",    zone:"interior" },
    { id:"INT-10", name:"Mesa 10", seats:6, x:55, y:12, shape:"rect-lg", zone:"interior" },
    { id:"INT-11", name:"Mesa 11", seats:4, x:55, y:38, shape:"rect",    zone:"interior" },
    { id:"INT-12", name:"Mesa 12", seats:4, x:55, y:60, shape:"rect",    zone:"interior" },
    { id:"INT-13", name:"Mesa 13", seats:2, x:55, y:83, shape:"round",   zone:"interior" },
    { id:"INT-14", name:"Mesa 14", seats:2, x:80, y:12, shape:"round",   zone:"interior" },
    { id:"INT-15", name:"Mesa 15", seats:4, x:80, y:30, shape:"rect",    zone:"interior" },
    { id:"INT-16", name:"Mesa 16", seats:6, x:80, y:52, shape:"rect-lg", zone:"interior" },
    { id:"INT-17", name:"Mesa 17", seats:4, x:80, y:76, shape:"rect",    zone:"interior" },
    { id:"INT-18", name:"Privado A", seats:8, x:42, y:46, shape:"oval", zone:"interior" },
    { id:"INT-19", name:"Privado B", seats:6, x:42, y:70, shape:"oval", zone:"interior" },
    { id:"INT-20", name:"Barra",     seats:3, x:42, y:90, shape:"bar",  zone:"interior" },
  ],
  terraza: [
    { id:"TER-01", name:"Terraza 1",  seats:2, x:10, y:15, shape:"round",   zone:"terraza" },
    { id:"TER-02", name:"Terraza 2",  seats:2, x:10, y:42, shape:"round",   zone:"terraza" },
    { id:"TER-03", name:"Terraza 3",  seats:4, x:10, y:70, shape:"rect",    zone:"terraza" },
    { id:"TER-04", name:"Terraza 4",  seats:4, x:35, y:15, shape:"rect",    zone:"terraza" },
    { id:"TER-05", name:"Terraza 5",  seats:6, x:35, y:42, shape:"rect-lg", zone:"terraza" },
    { id:"TER-06", name:"Terraza 6",  seats:4, x:35, y:72, shape:"rect",    zone:"terraza" },
    { id:"TER-07", name:"Terraza 7",  seats:4, x:62, y:15, shape:"rect",    zone:"terraza" },
    { id:"TER-08", name:"Terraza 8",  seats:8, x:62, y:44, shape:"rect-lg", zone:"terraza" },
    { id:"TER-09", name:"Terraza 9",  seats:2, x:62, y:74, shape:"round",   zone:"terraza" },
    { id:"TER-10", name:"Fuente ☀️",  seats:6, x:85, y:40, shape:"oval",    zone:"terraza" },
  ],
  segundo: [
    { id:"2DO-01", name:"Salón A-1",  seats:6,  x:12, y:15, shape:"rect-lg", zone:"segundo" },
    { id:"2DO-02", name:"Salón A-2",  seats:6,  x:12, y:45, shape:"rect-lg", zone:"segundo" },
    { id:"2DO-03", name:"Salón A-3",  seats:4,  x:12, y:75, shape:"rect",    zone:"segundo" },
    { id:"2DO-04", name:"Salón B-1",  seats:8,  x:42, y:20, shape:"rect-lg", zone:"segundo" },
    { id:"2DO-05", name:"Salón B-2",  seats:6,  x:42, y:55, shape:"rect-lg", zone:"segundo" },
    { id:"2DO-06", name:"Salón B-3",  seats:4,  x:42, y:82, shape:"rect",    zone:"segundo" },
    { id:"2DO-07", name:"Suite 🌸",   seats:10, x:72, y:25, shape:"oval",    zone:"segundo" },
    { id:"2DO-08", name:"Suite 🏮",   seats:10, x:72, y:68, shape:"oval",    zone:"segundo" },
  ]
};